env: standard
runtime: nodejs16
service: about
handlers:
  - url: assets/(.+\.js)
  static_files: assets/\1
  upload: assets/(.+\.js)
  mime_type: 'text/javascript'

  - url: .*
    static_files: index.html
    upload: index.html