env: standard
runtime: nodejs16
service: about
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

    - url: /(.*\.js)$
      static_files: \1
      upload: (.*\.js)$
      mime_type: text/javascript

    - url: /(.*\..+)$
      static_files: \1
      upload: (.*\..+)$