env: standard
runtime: python27
api_version: 1
threadsafe: true
service: about
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always

  - url: /(.*)
    static_files: assets/\1
    upload: assets/(.*)
