env: standard
runtime: nodejs16
service: about
handlers:
  - url: /assets
    static_dir: assets
    secure: always

  - url: assets/(.*\.(js|css))$
    static_files: assets/\1
    upload: assets/.*\.(js|css)$
    secure: always

  - url: .*
    static_files: index.html
    upload: index.html
    secure: always