name: deploy 

# Controls when the workflow will run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: build the project
        run: npm run build
        
      - name: copy app.yaml file to the build directory
        run: cp app.yaml dist

      - name: cd to the build directory and deploy the project
        run: cd dist

      - uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - uses: google-github-actions/deploy-appengine@main
        with:
          working_directory: dist
          version: production
